package de.gozilalp.configSetup;

/**
 * This enum defines usable Look & Feels for this program.
 *
 * @author grumanda
 */
public enum DefinedLAFs {

    FLAT_LIGHT_LAF("FLAT_LIGHT_LAF"),
    FLAT_ARC_ORANGE_IJTHEME("FLAT_ARC_ORANGE_IJTHEME"),
    FLAT_ATOM_ONE_LIGHT_IJTHEME("FLAT_ATOM_ONE_LIGHT_IJTHEME"),
    FLAT_MATERIAL_LIGHTER_IJTHEME("FLAT_MATERIAL_LIGHTER_IJTHEME"),
    FLAT_LIGHT_OWL_IJTHEME("FLAT_LIGHT_OWL_IJTHEME"),
    FLAT_DARK_LAF("FLAT_DARK_LAF"),
    FLAT_MONOKAI_PRO_IJTHEME("FLAT_MONOKAI_PRO_IJTHEME"),
    FLAT_MATERIAL_DESIGN_DARK_IJTHEME("FLAT_MATERIAL_DESIGN_DARK_IJTHEME"),
    FLAT_ARC_DARK_IJTHEME("FLAT_ARC_DARK_IJTHEME"),
    FLAT_ONE_DARK_IJTHEME("FLAT_ONE_DARK_IJTHEME");

    private final String CONFIG_VALUE;

    DefinedLAFs(String configValue) {
        this.CONFIG_VALUE = configValue;
    }

    public String getCONFIG_VALUE() {
        return CONFIG_VALUE;
    }
}